server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3307/microservices
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
#
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

    application:
        name: USER-SERVICE

    # configuration servers common configuration that is used in every service
    config:
        import: "optional:configserver:http://localhost:8085"
    # - spring.config.import.configserver=http://localhost:8085

    # profiles:
    #     active: default
    
# eureka:
#     instance:
#         prefer-ip-address: true
#     client:
#         fetch-registry: true
#         register-with-eureka: true
#         service-url:
#             defaultZone: http://localhost:8761/eureka

#actuator configuration
management:
    health:
        circuitbreakers:
            enabled: true
    endpoints:
        web:
          exposure:
            include: health
    endpoint:
        health:
            show-details: always

resilience4j:
    circuitbreaker:
        instances:
            ratingHotelBreaker:
                registerHealthIndicator: true
                eventConsumerBufferSize: 10
                failureRateThreshold: 50
                minimumNumberOfCalls: 5
                automaticTransitionFromOpenToHalfOpenEnabled: True
                waitDurationInOpenState: 6s
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowSize: 10
                slidingWindowType: COUNT_BASED

retry:
    instances:
        ratingHotelBreaker:
            max-attempts: 3
            wait-duration: 5s