server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3307/microservices
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
#
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

    application:
        name: USER-SERVICE

    # configuration servers common configuration that is used in every service
    config:
        import: "optional:configserver:http://localhost:8085"

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://dev-15726617.okta.com/oauth2/default
            client:
                registration:
                    my-internal-client:
                        provider: okta
                        authorization-grant-type: client_credentials
                        scope: internal
                        client-id: 0oaosp0mw1gJxz4Fo5d7
                        client-secret: BOdze5qN3wlILmU0sHaqjpfWFPmoB59L7-a22FE5--geAu0KjRounRDS_X_v-srN

    # - spring.config.import.configserver=http://localhost:8085

    # profiles:
    #     active: default
    
# eureka:
#     instance:
#         prefer-ip-address: true
#     client:
#         fetch-registry: true
#         register-with-eureka: true
#         service-url:
#             defaultZone: http://localhost:8761/eureka

#actuator configuration
management:
    health:
        circuitbreakers:
            enabled: true
    endpoints:
        web:
          exposure:
            include: health
    endpoint:
        health:
            show-details: always

resilience4j:
    circuitbreaker:
        instances:
            ratingHotelBreaker:
                registerHealthIndicator: true
                eventConsumerBufferSize: 10
                failureRateThreshold: 50
                minimumNumberOfCalls: 5
                automaticTransitionFromOpenToHalfOpenEnabled: True
                waitDurationInOpenState: 6s
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowSize: 10
                slidingWindowType: COUNT_BASED

retry:
    instances:
        ratingHotelBreaker:
            max-attempts: 3
            wait-duration: 5s

resilience4j.ratelimiter:
    instances:
        userRateLimiter:
            limit-refresh-period: 4s
            limit-for-period: 2
            timeout-duration: 0s

okta:
    oauth2:
        issuer: https://dev-15726617.okta.com/oauth2/default
        audience: api://default